version: "3.9"
services:
  backend:
    build:
      context: ./BD
    container_name: guapitos-api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=http://localhost   # el dominio donde servirá nginx
      - DATABASE_URL=file:/data/dev.db # SQLite persistente
    volumes:
      - dbdata:/data
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
    container_name: guapitos-web
    environment:
      - VITE_API_URL=http://backend:3000   # IMPORTANTÍSIMO: el front llama al servicio "backend" en la red de Docker
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  dbdata:
