FROM node:20-alpine
WORKDIR /app

# Copiamos dependencias y Prisma
COPY package*.json ./
COPY prisma ./prisma

# 📌 Crear carpeta para volumen persistente
RUN mkdir -p /data

# Instalamos dependencias
RUN npm ci

# Copiamos el resto del código
COPY tsconfig.json ./
COPY src ./src

# Generamos Prisma Client y compilamos
RUN npx prisma generate
RUN npm run build

# Variables y puerto
ENV PORT=3000
EXPOSE 3000

CMD ["node", "dist/server.js"]
